anti_ban:
  enabled: true
  force_delay_after: 100
  force_delay_ms: 1000
  interval:
    max_ms: 200
    min_ms: 100
  max_concurrency: 50
  retry:
    backoff_ms: 500
    max_attempts: 3
base:
  enabled: false
  manual_only: true
  scope:
    block: true
    block_stock_lnk: true
    stock: true
day_k:
  enabled: true
  schedules:
  - action: append
    interval_seconds: 30
    name: 早盘日K
    time: 09:27:00
    type: once
  - action: replace
    interval_seconds: 30
    name: 收盘日K
    time: '15:05:00'
    type: once
  scope:
    block: true
    stock: true
raw:
  delays:
    max_ms: 200
    min_ms: 100
  enabled: true
  schedules:
  - interval_seconds: 30
    name: 开盘竞价
    time: 09:25:00
    type: once
  - end_time: '11:30:00'
    interval_seconds: 30
    name: 早盘连续竞价
    start_time: 09:30:30
    type: interval
  - end_time: '14:27:00'
    interval_seconds: 30
    name: 下午连续竞价
    start_time: '13:00:00'
    type: interval
  - interval_seconds: 30
    name: 收盘
    time: '15:00:00'
    type: once
  scope:
    block: true
    stock: true
  threads:
    block: 1
    stock: 30
special_pool:
  enabled: true
  schedules:
  - interval_seconds: 30
    name: 开盘竞价
    time: 09:25:00
    type: once
  - end_time: '11:30:00'
    interval_seconds: 30
    name: 早盘连续竞价
    start_time: 09:30:30
    type: interval
  - end_time: '14:27:00'
    interval_seconds: 30
    name: 下午连续竞价
    start_time: '13:00:00'
    type: interval
  - interval_seconds: 30
    name: 收盘
    time: '15:00:00'
    type: once
  scope:
    dt: true
    zb: true
    zrzt: true
    zt: true
cls_telegram:
  enabled: true
  schedules:
  - end_time: '22:00:00'
    interval_seconds: 60
    name: 电报持续采集
    start_time: '09:00:00'
    type: interval
  scope:
    gs: true
    hy: true
    sc: true
    zc: true
