common:
  ut: "8dec03ba335b81bf4ebdf7b29ec27d15"
  cb: "jQuery1"
  timeout: 10
  max_pages: 100

endpoints:
  board_concept:
    url: "https://push2.eastmoney.com/api/qt/clist/get"
    fid: "f62"
    po: "1"
    pz: "50"
    np: "1"
    fltt: "2"
    invt: "2"
    fs: "m:90+t:3"
    fields: "f12,f14,f2,f3,f62,f184,f66,f69,f72,f75,f78,f81,f84,f87,f124,f140,f141,f204,f205"

  board_industry:
    url: "https://push2.eastmoney.com/api/qt/clist/get"
    fid: "f62"
    po: "1"
    pz: "50"
    np: "1"
    fltt: "2"
    invt: "2"
    fs: "m:90+s:4"
    fields: "f12,f14,f2,f3,f62,f184,f66,f69,f72,f75,f78,f81,f84,f87,f124,f140,f141,f204,f205"


  board_info:
    url: "https://push2.eastmoney.com/api/qt/stock/get"
    invt: "2"
    fltt: "2"
    fields: "f50"
    wbp2u: "3951356261349626|0|1|0|web"
    dect: "1"
    _: "1768623753902"









  stock_snapshot:
    url: "https://push2.eastmoney.com/api/qt/stock/get"
    invt: "2"
    fltt: "1"
    wbp2u: "|0|0|0|web"
    dect: "1"
    _: "1767444457994"
    fields: "f57,f58,f43,f169,f170,f47,f48,f168,f116,f117,f137,f140,f143,f146,f149,f162,f167,f193,f194,f195,f196,f197"